name: Node.js CI with Docker Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm run build --if-present

    # Step to build Docker image
    - name: Build Docker image
      run: |
        docker build -t inventory-service-image:latest .

    # Step to tag the Docker image
    - name: Tag Docker image
      run: |
        docker tag inventory-service-image:latest frhassan/imagesrepository:latest

    # Step to publish Docker image to Docker Hub
    - name: Publish Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: frhassan/imagesrepository
