name: Deploy Docker Image from Docker Hub (Self-Hosted Runner)

on:
  workflow_run:
    workflows: ["Node.js CI with Docker Build and Publish"]  # CI workflow name
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only on success
    runs-on: self-hosted  # Self-hosted runner where deployment happens

    steps:
      - name: Checkout Repository (Optional)
        uses: actions/checkout@v4

      - name: Pull Docker Image from Docker Hub
        run: docker pull frhassan/imagesrepository:latest

      - name: Run Docker Container
        run: |
          docker run -d --name myapp -p 3000:3000 frhassan/imagesrepository:latest
