name: Deploy Docker Image on Local Machine

on:
  workflow_run:
    workflows: ["Node.js CI with Docker Build and Publish"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted  # Runs on your local machine!

    steps:
      - name: Pull Docker Image from Docker Hub
        shell: pwsh
        run: |
          docker pull frhassan/imagesrepository:latest

      - name: Stop and Remove Previous Container (if exists)
        shell: pwsh
        run: |
          $container = docker ps -aq -f name=my-local-container
          if ($container) {
            docker stop my-local-container
            docker rm my-local-container
          }

      - name: Run Docker Container Locally
        shell: pwsh
        run: |
          docker run -d -p 8080:80 --name my-local-container frhassan/imagesrepository:latest

      - name: Verify Running Containers
        shell: pwsh
        run: |
          docker ps

      - name: Check App Health (Optional)
        shell: pwsh
        run: |
          Start-Sleep -Seconds 5
          Invoke-WebRequest -Uri http://localhost:8080 -UseBasicParsing
