name: Deploy Docker Image from Docker Hub (Self-Hosted Runner)

on:
  workflow_run:
    workflows: ["Node.js CI with Docker Build and Publish"]  # CI workflow name
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only on success
    runs-on: self-hosted  # Self-hosted runner where deployment happens

    steps:
      - name: Checkout Repository (Optional)
        uses: actions/checkout@v4

      - name: Pull Docker Image from Docker Hub
        run: docker pull frhassan/imagesrepository:latest

      - name: Stop Previous Container (Optional but recommended)
        shell: pwsh  # Ensure PowerShell is used
        run: |
          # Stop and remove the previous container if it exists
          if (docker ps -q -f "name=myapp") {
              docker stop myapp
              docker rm myapp
          }

      - name: Run Docker Container
        run: |
          docker run -d --name myapp -p 8080:80 frhassan/imagesrepository:latest
