
name: Deploy Docker Image on Local Machine

on:
  workflow_run:
    workflows: ["Node.js CI with Docker Build and Publish"]
    types:
      - completed  # Trigger CD after CI completes

jobs:
  deploy:
    runs-on: self-hosted  # THIS makes it run on your local machine!

    steps:
      - name: Pull Docker Image from Docker Hub
        shell: bash
        run: |
          docker pull frhassan/imagesrepository:latest

      - name: Stop and Remove Previous Container (if exists)
        shell: bash
        run: |
          if [ $(docker ps -aq -f name=my-local-container) ]; then
            docker stop my-local-container
            docker rm my-local-container
          fi

      - name: Run Docker Container Locally
        shell: bash
        run: |
          docker run -d -p 8080:80 --name my-local-container frhassan/imagesrepository:latest

      - name: Verify Running Containers
        shell: bash
        run: docker ps

      - name: Check App Health (Optional)
        shell: bash
        run: |
          echo "Waiting for the container to be ready..."
          sleep 5
          curl -v http://localhost:8080 || echo "App not responding yet!"
