name: Deploy Docker Image from Docker Hub (Self-Hosted Runner)

on:
  workflow_run:
    workflows: ["Node.js CI with Docker Build and Publish"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout Repository (Optional)
        uses: actions/checkout@v4

      - name: Pull Docker Image from Docker Hub
        run: docker pull frhassan/imagesrepository:latest

      - name: Stop and Remove Existing Docker Container
        shell: bash
        run: |
          if [ $(docker ps -q -f "name=myapp") ]; then
            docker stop myapp
            docker rm myapp
          else
            echo "No existing container named 'myapp' found."
          fi

      - name: Run Docker Container
        run: |
          docker run -d --name myapp -p 3000:3000 frhassan/imagesrepository:latest
